### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by kutycoi123** [rubikvn/rubikvn#2]
Hiện đang có 2 lựa chọn MVC framework:
- Sanic (Python)
- Express (Nodejs)

**Comment by trungams** [comment]
django hoặc flask nữa =))

**Comment by kutycoi123** [comment]
T đang thiên về flask hoặc express hơn, vì 2 cái này đơn giản mà có nhiều doc, tut nên dễ cho việc học và tìm kiếm.

**Comment by xpoko** [comment]
express để cho trung thành tạ

**Comment by trungams** [comment]
express để cho trung học js

**Comment by kutycoi123** [comment]
Bậy nào, Trung cái đéo gì chả giỏi =)))

**Comment by xpoko** [comment]
hợp lý

**Comment by kutycoi123** [comment]
Thế chọn express nhé, phần template cho front-end thì giang tự tìm hiểu đi.

**Comment by trungams** [comment]
thế lâm lead thôi

**Comment by kutycoi123** [comment]
:( Có 3 thằng thì lead cái gì =)))))

**Comment by xpoko** [comment]
ok espresso
