### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by kutycoi123** [rubikvn/rubikvn#3]
Chọn database cho app. Ae đề xuất đê, với express thì tôi mới dùng thằng mongoDB thôi. Relational db kiểu như MySQL thì cũng đc support khá tốt ở nodejs.

**Comment by xpoko** [comment]
mongoloidDB thì sẽ phải học

**Comment by trungams** [comment]
nên dùng relational vì phần lớn model đều có chung attributes, không nhất thiết phải bổ sung thêm cột trong db cho riêng cá nhân nào cả. t đã dùng qua 2 cái lớn là postgres và mysql. ngoài ra thì mariadb cũng là một lựa chọn (có vẻ) tốt hơn mysql

**Comment by kutycoi123** [comment]
Tại sao mariadb lại tốt hơn hả trung?

**Comment by trungams** [comment]
à k =)) vừa đọc lại thì thấy nó na ná nhau, mariadb cũng chỉ là fork của mysql, dùng cái nào thì do sở thích cá nhân. nhưng hiện tại thì mariadb có mã nguồn mở, trong khi mysql do oracle quản lý

**Comment by kutycoi123** [comment]
Thế 1 vote cho mysql <3

**Comment by xpoko** [comment]
mysql thoy
